import type { GetServerSideProps, NextPage, NextPageContext } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { getSession, signIn, signOut, useSession } from 'next-auth/react';

import { getStripe } from '@app/utils';

import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  const handleCreateCheckoutSession = async () => {
    const res = await fetch('/api/stripe/create-checkout-session', {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
      },
      body: JSON.stringify({
        price: 'price_1JaQIdFj6NPGX7Qvv0XYYdyv',
      }),
    });

    const data = await res.json();

    const stripe = await getStripe();

    stripe?.redirectToCheckout({ sessionId: data.sessionId });
  };

  const handleCreatePortal = async () => {
    const res = await fetch('/api/stripe/create-portal', {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
      },
    });

    const data = await res.json();

    const url = data.url;

    window.location.assign(url);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>

        {session!! ? (
          <>
            <button onClick={() => signOut()}>Sign out</button>
            <button onClick={handleCreateCheckoutSession}>Buy</button>
            <button onClick={handleCreatePortal}>Manage Subscription</button>
          </>
        ) : (
          <button onClick={() => signIn()}>Sign in</button>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  return {
    props: {
      session: await getSession(context),
    },
  };
};

export default Home;
